import type { Product } from './types'

export const categories = [
  { id: 'cervejas-lata', label: 'Cervejas Lata', icon: 'beer-can' },
  { id: 'cervejas-300-unidades', label: 'Cervejas 300ml', icon: 'beer-bottle' },
  { id: 'cervejas-300-caixa', label: 'Cervejas 300 ml — Caixa', icon: 'crate' },
  { id: 'long-necks', label: 'Cervejas Long Neck', icon: 'beer-bottle' },
  { id: 'zero-alcool', label: 'Cervejas Zero Álcool', icon: 'zero-beer' },
  { id: 'energeticos', label: 'Energéticos', icon: 'bolt' },
  { id: 'refrigerantes', label: 'Refrigerantes', icon: 'soda' },
  { id: 'whiskys', label: 'Whiskys', icon: 'whisky' },
  { id: 'vodkas', label: 'Vodkas', icon: 'bottle' },
  { id: 'gins', label: 'Gins', icon: 'cocktail' },
  { id: 'cachacas', label: 'Cachaças', icon: 'bottle' },
  { id: 'vinhos', label: 'Vinhos', icon: 'wine' },
  { id: 'espumantes', label: 'Espumantes', icon: 'sparkling' },
  { id: 'licores', label: 'Licores', icon: 'liqueur' },
  { id: 'bomboniere', label: 'Bomboniere', icon: 'candy' },
] as const

export const brands = [
  { name: "Heineken", image: null, accent: "#118847" },
  { name: "Brahma", image: "/assets/brands/brahma.jpg", accent: "#d5352c" },
  { name: "Skol", image: null, accent: "#f3c300" },
  { name: "Budweiser", image: null, accent: "#c62828" },
  { name: "Spaten", image: null, accent: "#0f6b44" },
  { name: "Original", image: null, accent: "#d9b446" },
  { name: "Bohemia", image: null, accent: "#8b3f2a" },
  { name: "Devassa", image: null, accent: "#d5b13b" },
  { name: "Stella Artois", image: "/assets/brands/stella.jpg", accent: "#c23338" },
  { name: "Michelob Ultra", image: "/assets/brands/michelob.jpg", accent: "#071f48" },
  { name: "Corona", image: null, accent: "#d2a64a" },
  { name: "Amstel", image: null, accent: "#d57a28" },
  { name: "Jack Daniel's", image: null, accent: "#111111" },
  { name: "Smirnoff", image: null, accent: "#b3262e" },
  { name: "Monster", image: null, accent: "#2f8f2f" },
  { name: "Ypióca", image: null, accent: "#c98a1e" },
] as const

export const products: Product[] = [
  { id: 'vinhos-san-jose', name: 'San José', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 5.00, image: '/assets/products/vinhos/san-jose.png', kind: 'common' },
  { id: 'vinhos-dom-bento', name: 'Dom Bento', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 5.50, image: '/assets/products/vinhos/dom-bento.png', kind: 'common' },
  { id: 'vinhos-sao-braz', name: 'São Braz', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 7.00, image: '/assets/products/vinhos/sao-braz.png', kind: 'common' },
  { id: 'vinhos-quinta-do-morgado-tinto-suave', name: 'Quinta do Morgado Tinto Suave', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 17.80, image: '/assets/products/vinhos/quinta-do-morgado-tinto-suave.png', kind: 'common' },
  { id: 'vinhos-quinta-do-morgado-branco-suave', name: 'Quinta do Morgado Branco Suave', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 19.80, image: '/assets/products/vinhos/quinta-do-morgado-branco-suave.png', kind: 'common' },
  { id: 'vinhos-quinta-do-morgado-tinto-seco', name: 'Quinta do Morgado Tinto Seco', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 19.80, image: '/assets/products/vinhos/quinta-do-morgado-tinto-seco.png', kind: 'common' },
  { id: 'vinhos-o-gaucho-tinto-suave', name: 'O Gaúcho Tinto Suave', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 18.80, image: '/assets/products/vinhos/o-gaucho-tinto-suave.png', kind: 'common' },
  { id: 'vinhos-o-gaucho-tinto-seco', name: 'O Gaúcho Tinto Seco', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 18.80, image: '/assets/products/vinhos/o-gaucho-tinto-seco.png', kind: 'common' },
  { id: 'vinhos-o-gaucho-rose-suave', name: 'O Gaúcho Rosé Suave', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 19.80, image: '/assets/products/vinhos/o-gaucho-rose-suave.png', kind: 'common' },
  { id: 'vinhos-reservado-sweet-branco', name: 'Reservado Sweet Branco', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 42.80, image: '/assets/products/vinhos/reservado-sweet-branco.png', kind: 'common' },
  { id: 'vinhos-reservado-sweet-rose', name: 'Reservado Sweet Rosé', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 42.80, image: '/assets/products/vinhos/reservado-sweet-rose.png', kind: 'common' },
  { id: 'vinhos-reservado-sweet-red', name: 'Reservado Sweet Red', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 42.80, image: '/assets/products/vinhos/reservado-sweet-red.png', kind: 'common' },
  { id: 'vinhos-santa-helena-carmenere', name: 'Santa Helena Carmenère', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/santa-helena-carmenere.png', kind: 'common' },
  { id: 'vinhos-santa-helena-rose', name: 'Santa Helena Rosé', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/santa-helena-rose.png', kind: 'common' },
  { id: 'vinhos-santa-helena-malbec', name: 'Santa Helena Malbec', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/santa-helena-malbec.png', kind: 'common' },
  { id: 'vinhos-santa-helena-merlot', name: 'Santa Helena Merlot', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/santa-helena-merlot.png', kind: 'common' },
  { id: 'vinhos-pergula-tinto-suave', name: 'Pérgula Tinto Suave', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 32.80, image: '/assets/products/vinhos/pergula-tinto-suave.png', kind: 'common' },
  { id: 'vinhos-pergula-branco-suave', name: 'Pérgula Branco Suave', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/pergula-branco-suave.png', kind: 'common' },
  { id: 'vinhos-pergula-tinto-seco-bordo', name: 'Pérgula Tinto Seco Bordô', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/pergula-tinto-seco-bordo.png', kind: 'common' },
  { id: 'vinhos-pergula-tinto-suave-bordo', name: 'Pérgula Tinto Suave Bordô', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 39.80, image: '/assets/products/vinhos/pergula-tinto-suave-bordo.png', kind: 'common' },
  { id: 'vinhos-casal-garcia-sweet-branco', name: 'Casal Garcia Sweet Branco', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 86.80, image: '/assets/products/vinhos/casal-garcia-sweet-branco.png', kind: 'common' },
  { id: 'vinhos-casal-garcia-sweet-rose', name: 'Casal Garcia Sweet Rosé', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 86.80, image: '/assets/products/vinhos/casal-garcia-sweet-rose.png', kind: 'common' },
  { id: 'vinhos-casal-garcia-tinto', name: 'Casal Garcia Tinto', category: 'Vinhos', categoryId: 'vinhos', size: '', price: 86.80, image: '/assets/products/vinhos/casal-garcia-tinto.png', kind: 'common' },
  { id: 'whiskys-old-parr-1l', name: 'Old Parr', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 129.90, image: '/assets/products/whiskys/old-parr-1l.png', kind: 'common' },
  { id: 'whiskys-old-parr-750ml', name: 'Old Parr', category: 'Whiskys', categoryId: 'whiskys', size: '750ml', price: 109.90, image: '/assets/products/whiskys/old-parr-750ml.png', kind: 'common' },
  { id: 'whiskys-chivas-regal-1l', name: 'Chivas Regal', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 106.00, image: '/assets/products/whiskys/chivas-regal-1l.png', kind: 'common' },
  { id: 'whiskys-buchanan-s-1l', name: "Buchanan's", category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 179.80, image: '/assets/products/whiskys/buchanans-1l.png', kind: 'common' },
  { id: 'whiskys-royal-salute-1l', name: 'Royal Salute', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 850.00, image: '/assets/products/whiskys/royal-salute-1l.png', kind: 'common' },
  { id: 'whiskys-jack-daniel-s-tradicional-1l', name: "Jack Daniel's Tradicional", category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 129.90, image: '/assets/products/whiskys/jack-daniels-tradicional-1l.png', kind: 'common' },
  { id: 'whiskys-jack-daniel-s-honey-1l', name: "Jack Daniel's Honey", category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 129.90, image: '/assets/products/whiskys/jack-daniels-honey-1l.png', kind: 'common' },
  { id: 'whiskys-jack-daniel-s-fire-1l', name: "Jack Daniel's Fire", category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 129.90, image: '/assets/products/whiskys/jack-daniels-fire-1l.png', kind: 'common' },
  { id: 'whiskys-jack-daniel-s-maca-verde-1l', name: "Jack Daniel's Maçã Verde", category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 129.90, image: '/assets/products/whiskys/jack-daniels-apple-1l.png', kind: 'common' },
  { id: 'whiskys-red-label-1l', name: 'Red Label', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 89.80, image: '/assets/products/whiskys/red-label-1l.png', kind: 'common' },
  { id: 'whiskys-black-label-1l', name: 'Black Label', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 169.90, image: '/assets/products/whiskys/black-label-1l.png', kind: 'common' },
  { id: 'whiskys-double-black-1l', name: 'Double Black', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 199.90, image: '/assets/products/whiskys/double-black-1l.png', kind: 'common' },
  { id: 'whiskys-gold-label-700ml', name: 'Gold Label', category: 'Whiskys', categoryId: 'whiskys', size: '700ml', price: 225.00, image: '/assets/products/whiskys/gold-label-700ml.png', kind: 'common' },
  { id: 'whiskys-ballantine-s-1l', name: "Ballantine's", category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 74.70, image: '/assets/products/whiskys/ballantines-1l.png', kind: 'common' },
  { id: 'whiskys-cavalo-branco-1l', name: 'Cavalo Branco', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 64.90, image: '/assets/products/whiskys/white-horse-1l.png', kind: 'common' },
  { id: 'whiskys-black-white-1l', name: 'Black & White', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 59.90, image: '/assets/products/whiskys/black-white-1l.png', kind: 'common' },
  { id: 'whiskys-black-white-750ml', name: 'Black & White', category: 'Whiskys', categoryId: 'whiskys', size: '750ml', price: 48.80, image: '/assets/products/whiskys/black-white-750ml.png', kind: 'common' },
  { id: 'whiskys-passport-1l', name: 'Passport', category: 'Whiskys', categoryId: 'whiskys', size: '1L', price: 49.90, image: '/assets/products/whiskys/passport-1l.png', kind: 'common' },
  { id: 'cachacas-aviador', name: 'Aviador', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 129.90, image: '/assets/products/cachacas/aviador.png', kind: 'common' },
  { id: 'cachacas-sagatiba-prata', name: 'Sagatiba Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 40.00, image: '/assets/products/cachacas/sagatiba-prata.png', kind: 'common' },
  { id: 'cachacas-busca-brisa', name: 'Busca Brisa', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 54.90, image: '/assets/products/cachacas/busca-brisa.png', kind: 'common' },
  { id: 'cachacas-cachaca-salinas', name: 'Cachaça Salinas', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 80.00, image: '/assets/products/cachacas/salinas.png', kind: 'common' },
  { id: 'cachacas-bananazinha', name: 'Bananazinha', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 45.80, image: '/assets/products/cachacas/bananazinha.png', kind: 'common' },
  { id: 'cachacas-ypioca-150', name: 'Ypióca 150', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 58.50, image: '/assets/products/cachacas/ypioca-150.png', kind: 'common' },
  { id: 'cachacas-ypioca-160', name: 'Ypióca 160', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 79.80, image: '/assets/products/cachacas/ypioca-160.png', kind: 'common' },
  { id: 'cachacas-ypioca-guarana', name: 'Ypióca Guaraná', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 22.80, image: '/assets/products/cachacas/ypioca-guarana.png', kind: 'common' },
  { id: 'cachacas-ypioca-lima-limao', name: 'Ypióca Lima Limão', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 22.80, image: '/assets/products/cachacas/ypioca-lima-limao.png', kind: 'common' },
  { id: 'cachacas-ypioca-mestra-ouro', name: 'Ypióca Mestra Ouro', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 27.90, image: '/assets/products/cachacas/ypioca-mestra-ouro.png', kind: 'common' },
  { id: 'cachacas-ypioca-mestra-prata', name: 'Ypióca Mestra Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 19.90, image: '/assets/products/cachacas/ypioca-mestra-prata.png', kind: 'common' },
  { id: 'cachacas-ypioca-ouro', name: 'Ypióca Ouro', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 18.00, image: '/assets/products/cachacas/ypioca-ouro.png', kind: 'common' },
  { id: 'cachacas-ypioca-prata', name: 'Ypióca Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 15.00, image: '/assets/products/cachacas/ypioca-prata.png', kind: 'common' },
  { id: 'cachacas-51-ouro', name: '51 Ouro', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 15.00, image: '/assets/products/cachacas/51-ouro.png', kind: 'common' },
  { id: 'cachacas-51-prata', name: '51 Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 12.00, image: '/assets/products/cachacas/51-prata.png', kind: 'common' },
  { id: 'cachacas-51-mel', name: '51 Mel', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 28.00, image: '/assets/products/cachacas/51-mel.png', kind: 'common' },
  { id: 'cachacas-pitu-prata', name: 'Pitú Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 12.00, image: '/assets/products/cachacas/pitu-prata.png', kind: 'common' },
  { id: 'cachacas-pitu-amarelinha', name: 'Pitú Amarelinha', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 18.00, image: '/assets/products/cachacas/pitu-amarelinha.png', kind: 'common' },
  { id: 'cachacas-montilla-carta-branca', name: 'Montilla Carta Branca', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 28.00, image: '/assets/products/cachacas/montilla-carta-branca.png', kind: 'common' },
  { id: 'cachacas-montilla-carta-ouro-envelhecida', name: 'Montilla Carta Ouro Envelhecida', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 99.00, image: '/assets/products/cachacas/montilla-carta-ouro-envelhecida.png', kind: 'common' },
  { id: 'cachacas-pingo-de-ouro', name: 'Pingo de Ouro', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 12.80, image: '/assets/products/cachacas/pingo-de-ouro.png', kind: 'common' },
  { id: 'cachacas-zinebra-roxs-verde', name: 'Zinebra Roxs Verde', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 12.00, image: '/assets/products/cachacas/zinebra-roxs-prata.png', kind: 'common' },
  { id: 'cachacas-zinebra-roxs-prata', name: 'Zinebra Roxs Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 12.00, image: '/assets/products/cachacas/zinebra-roxs-verde.png', kind: 'common' },
  { id: 'cachacas-parati-prata', name: 'Parati Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 10.00, image: '/assets/products/cachacas/parati-prata.png', kind: 'common' },
  { id: 'cachacas-parati-ouro', name: 'Parati Ouro', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 10.00, image: '/assets/products/cachacas/parati-ouro.png', kind: 'common' },
  { id: 'cachacas-douradinha-prata', name: 'Douradinha Prata', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 9.00, image: '/assets/products/cachacas/douradinha-prata.png', kind: 'common' },
  { id: 'cachacas-douradinha-ouro', name: 'Douradinha Ouro', category: 'Cachaças', categoryId: 'cachacas', size: '', price: 9.00, image: '/assets/products/cachacas/douradinha-ouro.png', kind: 'common' },
  { id: 'vodkas-ciroc', name: 'Cîroc', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 139.90, image: '/assets/products/vodkas/ciroc.png', kind: 'common' },
  { id: 'vodkas-absolut', name: 'Absolut', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 78.70, image: '/assets/products/vodkas/absolut.png', kind: 'common' },
  { id: 'vodkas-smirnoff-1l', name: 'Smirnoff', category: 'Vodkas', categoryId: 'vodkas', size: '1L', price: 35.80, image: '/assets/products/vodkas/smirnoff.png', kind: 'common' },
  { id: 'vodkas-orloff-1l', name: 'Orloff', category: 'Vodkas', categoryId: 'vodkas', size: '1L', price: 32.00, image: '/assets/products/vodkas/orloff.png', kind: 'common' },
  { id: 'vodkas-slova-tradicional', name: 'Slova Tradicional', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 13.80, image: '/assets/products/vodkas/slova-tradicional.png', kind: 'common' },
  { id: 'vodkas-slova-blueberry', name: 'Slova Blueberry', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 13.80, image: '/assets/products/vodkas/slova-blueberry.png', kind: 'common' },
  { id: 'vodkas-slova-frutas-vermelhas', name: 'Slova Frutas Vermelhas', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 13.80, image: '/assets/products/vodkas/slova-frutas-vermelhas.png', kind: 'common' },
  { id: 'vodkas-slova-maracuja', name: 'Slova Maracujá', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 13.80, image: '/assets/products/vodkas/slova-maracuja.png', kind: 'common' },
  { id: 'vodkas-slova-limao', name: 'Slova Limão', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 13.80, image: '/assets/products/vodkas/slova-limao.png', kind: 'common' },
  { id: 'vodkas-slova-kiwi', name: 'Slova Kiwi', category: 'Vodkas', categoryId: 'vodkas', size: '', price: 13.80, image: '/assets/products/vodkas/slova-kiwi.png', kind: 'common' },
  { id: 'gins-tanqueray', name: 'Tanqueray', category: 'Gins', categoryId: 'gins', size: '', price: 99.60, image: '/assets/products/gins/tanqueray.png', kind: 'common' },
  { id: 'gins-beefeater', name: 'Beefeater', category: 'Gins', categoryId: 'gins', size: '', price: 82.00, image: '/assets/products/gins/beefeater.png', kind: 'common' },
  { id: 'gins-gordons', name: 'Gordon’s', category: 'Gins', categoryId: 'gins', size: '', price: 55.00, image: '/assets/products/gins/gordons.png', kind: 'common' },
  { id: 'gins-bombay', name: 'Bombay', category: 'Gins', categoryId: 'gins', size: '', price: 82.00, image: '/assets/products/gins/bombay.png', kind: 'common' },
  { id: 'gins-rocks-tradicional', name: 'Rock’s Tradicional', category: 'Gins', categoryId: 'gins', size: '', price: 29.90, image: '/assets/products/gins/rocks-tradicional.png', kind: 'common' },
  { id: 'gins-rocks-morango', name: 'Rock’s Morango', category: 'Gins', categoryId: 'gins', size: '', price: 29.90, image: '/assets/products/gins/rocks-morango.png', kind: 'common' },
  { id: 'gins-rocks-melancia', name: 'Rock’s Melancia', category: 'Gins', categoryId: 'gins', size: '', price: 29.90, image: '/assets/products/gins/rocks-melancia.png', kind: 'common' },
  { id: 'gins-rocks-maca-verde', name: 'Rock’s Maçã Verde', category: 'Gins', categoryId: 'gins', size: '', price: 29.90, image: '/assets/products/gins/rocks-maca-verde.png', kind: 'common' },
  { id: 'gins-mancao-maromba-maca-verde', name: 'Manção Maromba Maçã Verde', category: 'Gins', categoryId: 'gins', size: '', price: 19.90, image: '/assets/products/gins/mancao-maromba-maca-verde.png', kind: 'common' },
  { id: 'gins-mancao-maromba-frutas-vermelhas', name: 'Manção Maromba Frutas Vermelhas', category: 'Gins', categoryId: 'gins', size: '', price: 19.90, image: '/assets/products/gins/mancao-maromba-frutas-vermelhas.png', kind: 'common' },
  { id: 'gins-mancao-maromba-frutas-tropicais', name: 'Manção Maromba Frutas Tropicais', category: 'Gins', categoryId: 'gins', size: '', price: 19.90, image: '/assets/products/gins/mancao-maromba-frutas-tropicais.png', kind: 'common' },
  { id: 'gins-mancao-maromba-uva', name: 'Manção Maromba Uva', category: 'Gins', categoryId: 'gins', size: '', price: 19.90, image: '/assets/products/gins/mancao-maromba-uva.png', kind: 'common' },
  { id: 'licores-campari-1l', name: 'Campari', category: 'Licores', categoryId: 'licores', size: '1L', price: 54.90, image: '/assets/products/licores/campari.webp', kind: 'common' },
  { id: 'licores-aperol-1l', name: 'Aperol', category: 'Licores', categoryId: 'licores', size: '1L', price: 48.00, image: '/assets/products/licores/aperol.webp', kind: 'common' },
  { id: 'licores-ballena-tradicional', name: 'Ballena Tradicional', category: 'Licores', categoryId: 'licores', size: '', price: 122.00, image: '/assets/products/licores/ballena-tradicional.webp', kind: 'common' },
  { id: 'licores-ballena-coco', name: 'Ballena Coco', category: 'Licores', categoryId: 'licores', size: '', price: 122.00, image: '/assets/products/licores/ballena-coco.webp', kind: 'common' },
  { id: 'licores-ballena-chocolate', name: 'Ballena Chocolate', category: 'Licores', categoryId: 'licores', size: '', price: 122.00, image: '/assets/products/licores/ballena-chocolate-caramelo.webp', kind: 'common' },
  { id: 'licores-martini-rosato', name: 'Martini Rosato', category: 'Licores', categoryId: 'licores', size: '', price: 64.80, image: '/assets/products/licores/martini-rosato.png', kind: 'common' },
  { id: 'licores-martini-bianco', name: 'Martini Bianco', category: 'Licores', categoryId: 'licores', size: '', price: 64.80, image: '/assets/products/licores/martini-bianco.webp', kind: 'common' },
  { id: 'licores-martini-extra-dry', name: 'Martini Extra Dry', category: 'Licores', categoryId: 'licores', size: '', price: 59.90, image: '/assets/products/licores/martini-extra-dry.webp', kind: 'common' },
  { id: 'licores-martini-rosso', name: 'Martini Rosso', category: 'Licores', categoryId: 'licores', size: '', price: 59.90, image: '/assets/products/licores/martini-rosso.webp', kind: 'common' },
  { id: 'espumantes-chandon', name: 'Chandon', category: 'Espumantes', categoryId: 'espumantes', size: '', price: 98.00, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'espumantes-lider', name: 'Líder', category: 'Espumantes', categoryId: 'espumantes', size: '', price: 13.80, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'espumantes-cereser', name: 'Cereser', category: 'Espumantes', categoryId: 'espumantes', size: '', price: 12.80, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'cervejas-lata-skol-350ml', name: 'Skol', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 3.70, image: '/assets/products/beer-350-new/skol-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 43.80 / 12 }] },
  { id: 'cervejas-lata-brahma-chopp-350ml', name: 'Brahma Chopp', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 3.70, image: '/assets/products/beer-350-new/brahma-chopp-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 43.80 / 12 }] },
  { id: 'cervejas-lata-brahma-duplo-malte-350ml', name: 'Brahma Duplo Malte', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 4.40, image: '/assets/products/beer-350-new/brahma-duplo-malte-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 49.80 / 12 }] },
  { id: 'cervejas-lata-original-350ml', name: 'Original', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 5.00, image: '/assets/products/beer-350-new/original-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 56.80 / 12 }] },
  { id: 'cervejas-lata-antarctica-350ml', name: 'Antarctica', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 4.00, image: '/assets/products/beer-350-new/antarctica-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 44.80 / 12 }] },
  { id: 'cervejas-lata-bohemia-350ml', name: 'Bohemia', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 4.00, image: '/assets/products/beer-350-new/bohemia-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 44.80 / 12 }] },
  { id: 'cervejas-lata-devassa-350ml', name: 'Devassa', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 3.50, image: '/assets/products/beer-350-new/devassa-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 39.80 / 12 }] },
  { id: 'cervejas-lata-amstel-350ml', name: 'Amstel', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 3.70, image: '/assets/products/beer-350/amstel.webp', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 43.80 / 12 }] },
  { id: 'cervejas-lata-budweiser-350ml', name: 'Budweiser', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 4.80, image: '/assets/products/beer-350/budweiser.webp', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 52.80 / 12 }] },
  { id: 'cervejas-lata-spaten-350ml', name: 'Spaten', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 5.00, image: '/assets/products/beer-350/spaten.webp', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 58.80 / 12 }] },
  { id: 'cervejas-lata-heineken-350ml', name: 'Heineken', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 5.60, image: '/assets/products/beer-350-new/heineken-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 64.80 / 12 }] },
  { id: 'cervejas-lata-corona-350ml', name: 'Corona', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 6.40, image: '/assets/products/beer-350/corona.webp', kind: 'common', cold: true, tiers: [{ qty: 8, unitPrice: 49.80 / 8 }] },
  { id: 'cervejas-lata-michelob-ultra-350ml', name: 'Michelob Ultra', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 5.50, image: '/assets/products/beer-350/michelob-ultra.webp', kind: 'common', cold: true, tiers: [{ qty: 8, unitPrice: 42.80 / 8 }] },
  { id: 'cervejas-lata-stella-350ml', name: 'Stella', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 5.50, image: '/assets/products/beer-350/stella.webp', kind: 'common', cold: true, tiers: [{ qty: 8, unitPrice: 42.80 / 8 }] },
  { id: 'cervejas-lata-stella-pure-gold-350ml', name: 'Stella Pure Gold', category: 'Cervejas Lata', categoryId: 'cervejas-lata', size: '350ml', price: 6.40, image: '/assets/products/beer-350/stella-pure-gold.webp', kind: 'common', cold: true, tiers: [{ qty: 8, unitPrice: 48.80 / 8 }] },
  { id: 'cervejas-300-unidades-skol-300ml', name: 'Skol', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.25, image: '/assets/products/placeholder.svg', kind: 'returnable', cold: true, tiers: [{ qty: 23, unitPrice: 64.80 / 23 }] },
  { id: 'cervejas-300-unidades-brahma-300ml', name: 'Brahma', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.25, image: '/assets/products/brahma-retornavel.jpg', kind: 'returnable', cold: true, tiers: [{ qty: 23, unitPrice: 63.80 / 23 }] },
  { id: 'cervejas-300-unidades-brahma-duplo-malte-300ml', name: 'Brahma Duplo Malte', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.25, image: '/assets/products/placeholder.svg', kind: 'returnable', cold: true, tiers: [{ qty: 23, unitPrice: 69.80 / 23 }] },
  { id: 'cervejas-300-unidades-bohemia-300ml', name: 'Bohemia', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.25, image: '/assets/products/placeholder.svg', kind: 'returnable', cold: true, tiers: [{ qty: 23, unitPrice: 64.80 / 23 }] },
  { id: 'cervejas-300-unidades-original-300ml', name: 'Original', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.50, image: '/assets/products/placeholder.svg', kind: 'returnable', cold: true, tiers: [{ qty: 23, unitPrice: 74.90 / 23 }] },
  { id: 'cervejas-300-unidades-devassa-300ml', name: 'Devassa', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.25, image: '/assets/products/placeholder.svg', kind: 'returnable', cold: true, tiers: [{ qty: 24, unitPrice: 58.80 / 24 }] },
  { id: 'cervejas-300-unidades-amstel-300ml', name: 'Amstel', category: 'Cervejas 300ml', categoryId: 'cervejas-300-unidades', size: '300ml', price: 3.25, image: '/assets/products/placeholder.svg', kind: 'returnable', cold: true, tiers: [{ qty: 24, unitPrice: 64.80 / 24 }] },
  { id: 'cervejas-300-caixa-skol-300ml', name: 'Skol — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 23 unidades', price: 64.80, basePrice: 3.25, packUnits: 23, image: '/assets/products/placeholder.svg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'cervejas-300-caixa-brahma-300ml', name: 'Brahma — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 23 unidades', price: 63.80, basePrice: 3.25, packUnits: 23, image: '/assets/products/brahma-retornavel.jpg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'cervejas-300-caixa-bohemia-300ml', name: 'Bohemia — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 23 unidades', price: 64.80, basePrice: 3.25, packUnits: 23, image: '/assets/products/placeholder.svg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'cervejas-300-caixa-original-300ml', name: 'Original — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 23 unidades', price: 74.90, basePrice: 3.50, packUnits: 23, image: '/assets/products/placeholder.svg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'cervejas-300-caixa-brahma-duplo-malte-300ml', name: 'Brahma Duplo Malte — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 23 unidades', price: 69.80, basePrice: 3.25, packUnits: 23, image: '/assets/products/placeholder.svg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'cervejas-300-caixa-devassa-300ml', name: 'Devassa — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 24 unidades', price: 58.80, basePrice: 3.25, packUnits: 24, image: '/assets/products/placeholder.svg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'cervejas-300-caixa-amstel-300ml', name: 'Amstel — Caixa', category: 'Cervejas 300 ml — Caixa', categoryId: 'cervejas-300-caixa', size: '300 ml · 24 unidades', price: 64.80, basePrice: 3.25, packUnits: 24, image: '/assets/products/placeholder.svg', kind: 'pack', cold: true, description: 'Caixa retornável. É necessário ter as garrafas para trocar.' },
  { id: 'long-necks-heineken-330ml', name: 'Heineken', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 6.80, image: '/assets/products/long-necks/heineken.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 79.20 / 12 }] },
  { id: 'long-necks-corona-330ml', name: 'Corona', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 7.60, image: '/assets/products/long-necks/corona.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 87.40 / 12 }] },
  { id: 'long-necks-budweiser-330ml', name: 'Budweiser', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 6.20, image: '/assets/products/long-necks/budweiser.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 71.40 / 12 }] },
  { id: 'long-necks-stella-330ml', name: 'Stella', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 6.80, image: '/assets/products/long-necks/stella.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 77.40 / 12 }] },
  { id: 'long-necks-stella-pure-gold-330ml', name: 'Stella Pure Gold', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 7.20, image: '/assets/products/long-necks/stella-pure-gold.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 84.90 / 12 }] },
  { id: 'long-necks-spaten-355ml', name: 'Spaten', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '355ml', price: 6.20, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 71.40 / 12 }] },
  { id: 'long-necks-eisenbahn-355ml', name: 'Eisenbahn', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '355ml', price: 5.80, image: '/assets/products/eisenbahn.jpg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 66.80 / 12 }] },
  { id: 'long-necks-michelob-ultra-330ml', name: 'Michelob Ultra', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 6.80, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 78.40 / 12 }] },
  { id: 'long-necks-amstel-ultra-330ml', name: 'Amstel Ultra', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 6.20, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 71.40 / 12 }] },
  { id: 'long-necks-ice-cabare-frutas-vermelhas-275ml', name: 'Ice Cabaré Frutas Vermelhas', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '275ml', price: 6.80, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 81.40 / 12 }] },
  { id: 'long-necks-ice-cabare-limao-275ml', name: 'Ice Cabaré Limão', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '275ml', price: 6.80, image: '/assets/products/long-necks/ice-cabare-limao.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 81.40 / 12 }] },
  { id: 'long-necks-ice-cabare-frutas-amarelas-275ml', name: 'Ice Cabaré Frutas Amarelas', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '275ml', price: 6.80, image: '/assets/products/long-necks/ice-cabare-frutas-amarelas.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 81.40 / 12 }] },
  { id: 'long-necks-ice-cabare-tangerina-275ml', name: 'Ice Cabaré Tangerina', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '275ml', price: 6.80, image: '/assets/products/long-necks/ice-cabare-tangerina.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 81.40 / 12 }] },
  { id: 'long-necks-smirnoff-ice-275ml', name: 'Smirnoff Ice', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '275ml', price: 6.20, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 71.40 / 12 }] },
  { id: 'long-necks-praya-330ml', name: 'Praya', category: 'Cervejas Long Neck', categoryId: 'long-necks', size: '330ml', price: 6.80, image: '/assets/products/long-necks/praya.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 77.40 / 12 }] },
  { id: 'zero-alcool-brahma-lata-zero-350ml', name: 'Brahma Lata Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '350ml', price: 4.10, image: '/assets/products/beer-350-new/brahma-zero-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 46.80 / 12 }] },
  { id: 'zero-alcool-heineken-lata-zero-350ml', name: 'Heineken Lata Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '350ml', price: 5.60, image: '/assets/products/beer-350-new/heineken-zero-v30.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 64.80 / 12 }] },
  { id: 'zero-alcool-budweiser-lata-zero-350ml', name: 'Budweiser Lata Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '350ml', price: 5.10, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 8, unitPrice: 39.20 / 8 }] },
  { id: 'zero-alcool-corona-lata-zero-350ml', name: 'Corona Lata Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '350ml', price: 6.40, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 8, unitPrice: 49.80 / 8 }] },
  { id: 'zero-alcool-budweiser-long-neck-zero-330ml', name: 'Budweiser Long Neck Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '330ml', price: 6.20, image: '/assets/products/zero-alcool/budweiser-long-neck-zero.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 71.40 / 12 }] },
  { id: 'zero-alcool-heineken-long-neck-zero-330ml', name: 'Heineken Long Neck Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '330ml', price: 7.20, image: '/assets/products/zero-alcool/heineken-long-neck-zero.png', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 86.40 / 12 }] },
  { id: 'zero-alcool-corona-long-neck-zero-330ml', name: 'Corona Long Neck Zero', category: 'Cervejas Zero Álcool', categoryId: 'zero-alcool', size: '330ml', price: 7.60, image: '/assets/products/placeholder.svg', kind: 'common', cold: true, tiers: [{ qty: 12, unitPrice: 87.40 / 12 }] },
  { id: 'energeticos-night-power-2l', name: 'Night Power', category: 'Energéticos', categoryId: 'energeticos', size: '2L', price: 12.80, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-bally-melancia-2l', name: 'Bally Melancia', category: 'Energéticos', categoryId: 'energeticos', size: '2L', price: 16.80, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-bally-maca-verde-2l', name: 'Bally Maçã Verde', category: 'Energéticos', categoryId: 'energeticos', size: '2L', price: 16.80, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-bally-coco-e-acai-2l', name: 'Bally Coco e Açaí', category: 'Energéticos', categoryId: 'energeticos', size: '2L', price: 16.80, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-red-bull-lata', name: 'Red Bull', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 9.90, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-tradicional-lata', name: 'Monster Tradicional', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-mango-loco-lata', name: 'Monster Mango Loco', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-ultra-lata', name: 'Monster Ultra', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-ultra-zero-lata', name: 'Monster Ultra Zero', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-zero-lata', name: 'Monster Zero', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-violeta-lata', name: 'Monster Violeta', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-melancia-lata', name: 'Monster Melancia', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'energeticos-monster-pessego-lata', name: 'Monster Pêssego', category: 'Energéticos', categoryId: 'energeticos', size: 'Lata', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-coca-cola-2l', name: 'Coca-Cola', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 12.00, image: '/assets/products/coca-cola.jpg', kind: 'common', cold: true },
  { id: 'refrigerantes-coca-cola-zero-2l', name: 'Coca-Cola Zero', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-cajuina-2l', name: 'Cajuína', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-cajuina-zero-2l', name: 'Cajuína Zero', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 12.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-sprite-2l', name: 'Sprite', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 10.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-fanta-laranja-2l', name: 'Fanta Laranja', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 10.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-fanta-uva-2l', name: 'Fanta Uva', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 10.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-guarana-2l', name: 'Guaraná', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 10.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-refri-cola-2l', name: 'Refri Cola', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 6.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-refri-guarana-2l', name: 'Refri Guaraná', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 6.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'refrigerantes-refri-laranja-2l', name: 'Refri Laranja', category: 'Refrigerantes', categoryId: 'refrigerantes', size: '2L', price: 6.00, image: '/assets/products/placeholder.svg', kind: 'common', cold: true },
  { id: 'bomboniere-caixa-de-bombom-garoto', name: 'Caixa de Bombom Garoto', category: 'Bomboniere', categoryId: 'bomboniere', size: '', price: 16.00, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'bomboniere-caixa-de-bombom-nestle', name: 'Caixa de Bombom Nestlé', category: 'Bomboniere', categoryId: 'bomboniere', size: '', price: 17.00, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'bomboniere-caixa-de-bombom-lacta', name: 'Caixa de Bombom Lacta', category: 'Bomboniere', categoryId: 'bomboniere', size: '', price: 17.00, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'bomboniere-trident', name: 'Trident', category: 'Bomboniere', categoryId: 'bomboniere', size: '', price: 3.00, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'bomboniere-trident-cereja', name: 'Trident Cereja', category: 'Bomboniere', categoryId: 'bomboniere', size: '', price: 3.00, image: '/assets/products/placeholder.svg', kind: 'common' },
  { id: 'bomboniere-trident-melancia', name: 'Trident Melancia', category: 'Bomboniere', categoryId: 'bomboniere', size: '', price: 3.00, image: '/assets/products/placeholder.svg', kind: 'common' },
]

export const productsByCategory = (categoryId: string) => products.filter(product => product.categoryId === categoryId)



